/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Run the ply2splat CLI directly.
 *
 * @param args - Array of command-line arguments (e.g. ["--input", "file.ply", "--output", "file.splat"])
 */
export declare function cli(args: Array<string>): void

/** Result of a PLY to SPLAT conversion. */
export interface ConversionResult {
  /** The converted SPLAT data */
  data: Buffer
  /** Number of splats in the result */
  count: number
}

/**
 * Convert PLY data to SPLAT format.
 *
 * @param plyData - PLY file contents as a Buffer
 * @param sort - Whether to sort splats by importance (default: true)
 * @returns Object containing the SPLAT data buffer and count
 */
export declare function convert(plyData: Buffer, sort?: boolean | undefined | null): ConversionResult

/**
 * Get the number of splats in a SPLAT data buffer.
 *
 * @param splatData - SPLAT file contents as a Buffer
 * @returns Number of splats in the data
 */
export declare function getSplatCount(splatData: Buffer): number
